version: "3"
services:
  node-api:
#    environment:
#      - NODE_ENV=development

    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/app
    container_name: node-api
    # expose:
    #  - "3000"
    ports:
      - "3000:3000"
#   command: npm run development
